# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Arcana.create(
  [
    { number: 0, name: '愚者' },
    { number: 1, name: '魔術師' },
    { number: 2, name: '女教皇' },
    { number: 3, name: '女帝' },
    { number: 4, name: '皇帝' },
    { number: 5, name: '法王' },
    { number: 6, name: '恋愛' },
    { number: 7, name: '戦車' },
    { number: 8, name: '正義' },
    { number: 9, name: '隠者' },
    { number: 10, name: '運命' },
    { number: 11, name: '剛毅' },
    { number: 12, name: '刑死者' },
    { number: 13, name: '死神' },
    { number: 14, name: '節制' },
    { number: 15, name: '悪魔' },
    { number: 16, name: '塔' },
    { number: 17, name: '星' },
    { number: 18, name: '月' },
    { number: 19, name: '太陽' },
    { number: 20, name: '審判' },
    { number: 21, name: '世界' },
    { number: 22, name: '信念' },
    { number: 23, name: '顧問官' },
  ]
)

Category.create(
  [
    { name: '通常' },
    { name: '宝魔' },
    { name: '集団ギロチン' },
    { name: 'DLC' }
  ]
)

ArcanaCombination.create(
  [
    { key_number: '00', first_arcana_number: 0, second_arcana_number: 0, result_arcana_number: 0 },
    { key_number: '01', first_arcana_number: 0, second_arcana_number: 1, result_arcana_number: 13 },
    { key_number: '02', first_arcana_number: 0, second_arcana_number: 2, result_arcana_number: 18 },
    { key_number: '03', first_arcana_number: 0, second_arcana_number: 3, result_arcana_number: 12 },
    { key_number: '04', first_arcana_number: 0, second_arcana_number: 4, result_arcana_number: 14 },
    { key_number: '05', first_arcana_number: 0, second_arcana_number: 5, result_arcana_number: 9 },
    { key_number: '06', first_arcana_number: 0, second_arcana_number: 6, result_arcana_number: 7 },
    { key_number: '07', first_arcana_number: 0, second_arcana_number: 7, result_arcana_number: 18 },
    { key_number: '08', first_arcana_number: 0, second_arcana_number: 8, result_arcana_number: 17 },
    { key_number: '09', first_arcana_number: 0, second_arcana_number: 9, result_arcana_number: 2 },
    { key_number: '010', first_arcana_number: 0, second_arcana_number: 10, result_arcana_number: 22 },
    { key_number: '011', first_arcana_number: 0, second_arcana_number: 11, result_arcana_number: 13 },
    { key_number: '012', first_arcana_number: 0, second_arcana_number: 12, result_arcana_number: 16 },
    { key_number: '013', first_arcana_number: 0, second_arcana_number: 13, result_arcana_number: 11 },
    { key_number: '014', first_arcana_number: 0, second_arcana_number: 14, result_arcana_number: 5 },
    { key_number: '015', first_arcana_number: 0, second_arcana_number: 15, result_arcana_number: 14 },
    { key_number: '016', first_arcana_number: 0, second_arcana_number: 16, result_arcana_number: 3 },
    { key_number: '017', first_arcana_number: 0, second_arcana_number: 17, result_arcana_number: 1 },
    { key_number: '018', first_arcana_number: 0, second_arcana_number: 18, result_arcana_number: 8 },
    { key_number: '019', first_arcana_number: 0, second_arcana_number: 19, result_arcana_number: 8 },
    { key_number: '020', first_arcana_number: 0, second_arcana_number: 20, result_arcana_number: 19 },
    { key_number: '022', first_arcana_number: 0, second_arcana_number: 22, result_arcana_number: 23 },
    { key_number: '023', first_arcana_number: 0, second_arcana_number: 23, result_arcana_number: 5 },
    { key_number: '11', first_arcana_number: 1, second_arcana_number: 1, result_arcana_number: 1 },
    { key_number: '12', first_arcana_number: 1, second_arcana_number: 2, result_arcana_number: 14 },
    { key_number: '13', first_arcana_number: 1, second_arcana_number: 3, result_arcana_number: 8 },
    { key_number: '14', first_arcana_number: 1, second_arcana_number: 4, result_arcana_number: 22 },
    { key_number: '15', first_arcana_number: 1, second_arcana_number: 5, result_arcana_number: 13 },
    { key_number: '16', first_arcana_number: 1, second_arcana_number: 6, result_arcana_number: 15 },
    { key_number: '17', first_arcana_number: 1, second_arcana_number: 7, result_arcana_number: 2 },
    { key_number: '18', first_arcana_number: 1, second_arcana_number: 8, result_arcana_number: 4 },
    { key_number: '19', first_arcana_number: 1, second_arcana_number: 9, result_arcana_number: 6 },
    { key_number: '110', first_arcana_number: 1, second_arcana_number: 10, result_arcana_number: 8 },
    { key_number: '111', first_arcana_number: 1, second_arcana_number: 11, result_arcana_number: 0 },
    { key_number: '112', first_arcana_number: 1, second_arcana_number: 12, result_arcana_number: 3 },
    { key_number: '113', first_arcana_number: 1, second_arcana_number: 13, result_arcana_number: 9 },
    { key_number: '114', first_arcana_number: 1, second_arcana_number: 14, result_arcana_number: 7 },
    { key_number: '115', first_arcana_number: 1, second_arcana_number: 15, result_arcana_number: 5 },
    { key_number: '116', first_arcana_number: 1, second_arcana_number: 16, result_arcana_number: 14 },
    { key_number: '117', first_arcana_number: 1, second_arcana_number: 17, result_arcana_number: 2 },
    { key_number: '118', first_arcana_number: 1, second_arcana_number: 18, result_arcana_number: 6 },
    { key_number: '119', first_arcana_number: 1, second_arcana_number: 19, result_arcana_number: 5 },
    { key_number: '120', first_arcana_number: 1, second_arcana_number: 20, result_arcana_number: 11 },
    { key_number: '122', first_arcana_number: 1, second_arcana_number: 22, result_arcana_number: 11 },
    { key_number: '123', first_arcana_number: 1, second_arcana_number: 23, result_arcana_number: 18 },
    { key_number: '22', first_arcana_number: 2, second_arcana_number: 2, result_arcana_number: 2 },
    { key_number: '23', first_arcana_number: 2, second_arcana_number: 3, result_arcana_number: 4 },
    { key_number: '24', first_arcana_number: 2, second_arcana_number: 4, result_arcana_number: 3 },
    { key_number: '25', first_arcana_number: 2, second_arcana_number: 5, result_arcana_number: 2 },
    { key_number: '26', first_arcana_number: 2, second_arcana_number: 6, result_arcana_number: 10 },
    { key_number: '27', first_arcana_number: 2, second_arcana_number: 7, result_arcana_number: 5 },
    { key_number: '28', first_arcana_number: 2, second_arcana_number: 8, result_arcana_number: 13 },
    { key_number: '29', first_arcana_number: 2, second_arcana_number: 9, result_arcana_number: 14 },
    { key_number: '210', first_arcana_number: 2, second_arcana_number: 10, result_arcana_number: 1 },
    { key_number: '211', first_arcana_number: 2, second_arcana_number: 11, result_arcana_number: 15 },
    { key_number: '212', first_arcana_number: 2, second_arcana_number: 12, result_arcana_number: 13 },
    { key_number: '213', first_arcana_number: 2, second_arcana_number: 13, result_arcana_number: 1 },
    { key_number: '214', first_arcana_number: 2, second_arcana_number: 14, result_arcana_number: 15 },
    { key_number: '215', first_arcana_number: 2, second_arcana_number: 15, result_arcana_number: 18 },
    { key_number: '216', first_arcana_number: 2, second_arcana_number: 16, result_arcana_number: 12 },
    { key_number: '217', first_arcana_number: 2, second_arcana_number: 17, result_arcana_number: 9 },
    { key_number: '218', first_arcana_number: 2, second_arcana_number: 18, result_arcana_number: 5 },
    { key_number: '219', first_arcana_number: 2, second_arcana_number: 19, result_arcana_number: 7 },
    { key_number: '220', first_arcana_number: 2, second_arcana_number: 20, result_arcana_number: 8 },
    { key_number: '222', first_arcana_number: 2, second_arcana_number: 22, result_arcana_number: 8 },
    { key_number: '223', first_arcana_number: 2, second_arcana_number: 23, result_arcana_number: 22 },
    { key_number: '33', first_arcana_number: 3, second_arcana_number: 3, result_arcana_number: 3 },
    { key_number: '34', first_arcana_number: 3, second_arcana_number: 4, result_arcana_number: 8 },
    { key_number: '35', first_arcana_number: 3, second_arcana_number: 5, result_arcana_number: 0 },
    { key_number: '36', first_arcana_number: 3, second_arcana_number: 6, result_arcana_number: 20 },
    { key_number: '37', first_arcana_number: 3, second_arcana_number: 7, result_arcana_number: 17 },
    { key_number: '38', first_arcana_number: 3, second_arcana_number: 8, result_arcana_number: 6 },
    { key_number: '39', first_arcana_number: 3, second_arcana_number: 9, result_arcana_number: 11 },
    { key_number: '310', first_arcana_number: 3, second_arcana_number: 10, result_arcana_number: 9 },
    { key_number: '311', first_arcana_number: 3, second_arcana_number: 11, result_arcana_number: 22 },
    { key_number: '312', first_arcana_number: 3, second_arcana_number: 12, result_arcana_number: 2 },
    { key_number: '313', first_arcana_number: 3, second_arcana_number: 13, result_arcana_number: 0 },
    { key_number: '314', first_arcana_number: 3, second_arcana_number: 14, result_arcana_number: 22 },
    { key_number: '315', first_arcana_number: 3, second_arcana_number: 15, result_arcana_number: 19 },
    { key_number: '316', first_arcana_number: 3, second_arcana_number: 16, result_arcana_number: 4 },
    { key_number: '317', first_arcana_number: 3, second_arcana_number: 17, result_arcana_number: 6 },
    { key_number: '318', first_arcana_number: 3, second_arcana_number: 18, result_arcana_number: 10 },
    { key_number: '319', first_arcana_number: 3, second_arcana_number: 19, result_arcana_number: 16 },
    { key_number: '320', first_arcana_number: 3, second_arcana_number: 20, result_arcana_number: 4 },
    { key_number: '322', first_arcana_number: 3, second_arcana_number: 22, result_arcana_number: 1 },
    { key_number: '323', first_arcana_number: 3, second_arcana_number: 23, result_arcana_number: 12 },
    { key_number: '44', first_arcana_number: 4, second_arcana_number: 4, result_arcana_number: 4 },
    { key_number: '45', first_arcana_number: 4, second_arcana_number: 5, result_arcana_number: 10 },
    { key_number: '46', first_arcana_number: 4, second_arcana_number: 6, result_arcana_number: 0 },
    { key_number: '47', first_arcana_number: 4, second_arcana_number: 7, result_arcana_number: 22 },
    { key_number: '48', first_arcana_number: 4, second_arcana_number: 8, result_arcana_number: 7 },
    { key_number: '49', first_arcana_number: 4, second_arcana_number: 9, result_arcana_number: 5 },
    { key_number: '410', first_arcana_number: 4, second_arcana_number: 10, result_arcana_number: 19 },
    { key_number: '411', first_arcana_number: 4, second_arcana_number: 11, result_arcana_number: 16 },
    { key_number: '412', first_arcana_number: 4, second_arcana_number: 12, result_arcana_number: 15 },
    { key_number: '413', first_arcana_number: 4, second_arcana_number: 13, result_arcana_number: 9 },
    { key_number: '414', first_arcana_number: 4, second_arcana_number: 14, result_arcana_number: 15 },
    { key_number: '415', first_arcana_number: 4, second_arcana_number: 15, result_arcana_number: 8 },
    { key_number: '416', first_arcana_number: 4, second_arcana_number: 16, result_arcana_number: 17 },
    { key_number: '417', first_arcana_number: 4, second_arcana_number: 17, result_arcana_number: 6 },
    { key_number: '418', first_arcana_number: 4, second_arcana_number: 18, result_arcana_number: 16 },
    { key_number: '419', first_arcana_number: 4, second_arcana_number: 19, result_arcana_number: 20 },
    { key_number: '420', first_arcana_number: 4, second_arcana_number: 20, result_arcana_number: 2 },
    { key_number: '422', first_arcana_number: 4, second_arcana_number: 22, result_arcana_number: 2 },
    { key_number: '423', first_arcana_number: 4, second_arcana_number: 23, result_arcana_number: 6 },
    { key_number: '55', first_arcana_number: 5, second_arcana_number: 5, result_arcana_number: 5 },
    { key_number: '56', first_arcana_number: 5, second_arcana_number: 6, result_arcana_number: 11 },
    { key_number: '57', first_arcana_number: 5, second_arcana_number: 7, result_arcana_number: 17 },
    { key_number: '58', first_arcana_number: 5, second_arcana_number: 8, result_arcana_number: 12 },
    { key_number: '59', first_arcana_number: 5, second_arcana_number: 9, result_arcana_number: 23 },
    { key_number: '510', first_arcana_number: 5, second_arcana_number: 10, result_arcana_number: 8 },
    { key_number: '511', first_arcana_number: 5, second_arcana_number: 11, result_arcana_number: 0 },
    { key_number: '512', first_arcana_number: 5, second_arcana_number: 12, result_arcana_number: 19 },
    { key_number: '513', first_arcana_number: 5, second_arcana_number: 13, result_arcana_number: 7 },
    { key_number: '514', first_arcana_number: 5, second_arcana_number: 14, result_arcana_number: 13 },
    { key_number: '515', first_arcana_number: 5, second_arcana_number: 15, result_arcana_number: 12 },
    { key_number: '516', first_arcana_number: 5, second_arcana_number: 16, result_arcana_number: 20 },
    { key_number: '517', first_arcana_number: 5, second_arcana_number: 17, result_arcana_number: 16 },
    { key_number: '518', first_arcana_number: 5, second_arcana_number: 18, result_arcana_number: 2 },
    { key_number: '519', first_arcana_number: 5, second_arcana_number: 19, result_arcana_number: 6 },
    { key_number: '520', first_arcana_number: 5, second_arcana_number: 20, result_arcana_number: 22 },
    { key_number: '522', first_arcana_number: 5, second_arcana_number: 22, result_arcana_number: 3 },
    { key_number: '523', first_arcana_number: 5, second_arcana_number: 23, result_arcana_number: 8 },
    { key_number: '66', first_arcana_number: 6, second_arcana_number: 6, result_arcana_number: 6 },
    { key_number: '67', first_arcana_number: 6, second_arcana_number: 7, result_arcana_number: 14 },
    { key_number: '68', first_arcana_number: 6, second_arcana_number: 8, result_arcana_number: 20 },
    { key_number: '69', first_arcana_number: 6, second_arcana_number: 9, result_arcana_number: 7 },
    { key_number: '610', first_arcana_number: 6, second_arcana_number: 10, result_arcana_number: 11 },
    { key_number: '611', first_arcana_number: 6, second_arcana_number: 11, result_arcana_number: 13 },
    { key_number: '612', first_arcana_number: 6, second_arcana_number: 12, result_arcana_number: 23 },
    { key_number: '613', first_arcana_number: 6, second_arcana_number: 13, result_arcana_number: 14 },
    { key_number: '614', first_arcana_number: 6, second_arcana_number: 14, result_arcana_number: 11 },
    { key_number: '615', first_arcana_number: 6, second_arcana_number: 15, result_arcana_number: 18 },
    { key_number: '616', first_arcana_number: 6, second_arcana_number: 16, result_arcana_number: 3 },
    { key_number: '617', first_arcana_number: 6, second_arcana_number: 17, result_arcana_number: 22 },
    { key_number: '618', first_arcana_number: 6, second_arcana_number: 18, result_arcana_number: 1 },
    { key_number: '619', first_arcana_number: 6, second_arcana_number: 19, result_arcana_number: 3 },
    { key_number: '620', first_arcana_number: 6, second_arcana_number: 20, result_arcana_number: 12 },
    { key_number: '622', first_arcana_number: 6, second_arcana_number: 22, result_arcana_number: 16 },
    { key_number: '623', first_arcana_number: 6, second_arcana_number: 23, result_arcana_number: 16 },
    { key_number: '77', first_arcana_number: 7, second_arcana_number: 7, result_arcana_number: 7 },
    { key_number: '78', first_arcana_number: 7, second_arcana_number: 8, result_arcana_number: 18 },
    { key_number: '79', first_arcana_number: 7, second_arcana_number: 9, result_arcana_number: 15 },
    { key_number: '710', first_arcana_number: 7, second_arcana_number: 10, result_arcana_number: 23 },
    { key_number: '711', first_arcana_number: 7, second_arcana_number: 11, result_arcana_number: 9 },
    { key_number: '712', first_arcana_number: 7, second_arcana_number: 12, result_arcana_number: 0 },
    { key_number: '713', first_arcana_number: 7, second_arcana_number: 13, result_arcana_number: 15 },
    { key_number: '714', first_arcana_number: 7, second_arcana_number: 14, result_arcana_number: 11 },
    { key_number: '715', first_arcana_number: 7, second_arcana_number: 15, result_arcana_number: 14 },
    { key_number: '716', first_arcana_number: 7, second_arcana_number: 16, result_arcana_number: 10 },
    { key_number: '717', first_arcana_number: 7, second_arcana_number: 17, result_arcana_number: 18 },
    { key_number: '718', first_arcana_number: 7, second_arcana_number: 18, result_arcana_number: 6 },
    { key_number: '719', first_arcana_number: 7, second_arcana_number: 19, result_arcana_number: 2 },
    { key_number: '720', first_arcana_number: 7, second_arcana_number: 20, result_arcana_number: nil },
    { key_number: '722', first_arcana_number: 7, second_arcana_number: 22, result_arcana_number: 6 },
    { key_number: '723', first_arcana_number: 7, second_arcana_number: 23, result_arcana_number: 19 },
    { key_number: '88', first_arcana_number: 8, second_arcana_number: 8, result_arcana_number: 8 },
    { key_number: '89', first_arcana_number: 8, second_arcana_number: 9, result_arcana_number: 1 },
    { key_number: '810', first_arcana_number: 8, second_arcana_number: 10, result_arcana_number: 4 },
    { key_number: '811', first_arcana_number: 8, second_arcana_number: 11, result_arcana_number: 23 },
    { key_number: '812', first_arcana_number: 8, second_arcana_number: 12, result_arcana_number: 6 },
    { key_number: '813', first_arcana_number: 8, second_arcana_number: 13, result_arcana_number: 0 },
    { key_number: '814', first_arcana_number: 8, second_arcana_number: 14, result_arcana_number: 4 },
    { key_number: '815', first_arcana_number: 8, second_arcana_number: 15, result_arcana_number: 0 },
    { key_number: '816', first_arcana_number: 8, second_arcana_number: 16, result_arcana_number: 19 },
    { key_number: '817', first_arcana_number: 8, second_arcana_number: 17, result_arcana_number: 3 },
    { key_number: '818', first_arcana_number: 8, second_arcana_number: 18, result_arcana_number: 15 },
    { key_number: '819', first_arcana_number: 8, second_arcana_number: 19, result_arcana_number: 12 },
    { key_number: '820', first_arcana_number: 8, second_arcana_number: 20, result_arcana_number: nil },
    { key_number: '822', first_arcana_number: 8, second_arcana_number: 22, result_arcana_number: 12 },
    { key_number: '823', first_arcana_number: 8, second_arcana_number: 23, result_arcana_number: 4 },
    { key_number: '99', first_arcana_number: 9, second_arcana_number: 9, result_arcana_number: 9 },
    { key_number: '910', first_arcana_number: 9, second_arcana_number: 10, result_arcana_number: 17 },
    { key_number: '911', first_arcana_number: 9, second_arcana_number: 11, result_arcana_number: 5 },
    { key_number: '912', first_arcana_number: 9, second_arcana_number: 12, result_arcana_number: 17 },
    { key_number: '913', first_arcana_number: 9, second_arcana_number: 13, result_arcana_number: 11 },
    { key_number: '914', first_arcana_number: 9, second_arcana_number: 14, result_arcana_number: 11 },
    { key_number: '915', first_arcana_number: 9, second_arcana_number: 15, result_arcana_number: 2 },
    { key_number: '916', first_arcana_number: 9, second_arcana_number: 16, result_arcana_number: 20 },
    { key_number: '917', first_arcana_number: 9, second_arcana_number: 17, result_arcana_number: 11 },
    { key_number: '918', first_arcana_number: 9, second_arcana_number: 18, result_arcana_number: 2 },
    { key_number: '919', first_arcana_number: 9, second_arcana_number: 19, result_arcana_number: 15 },
    { key_number: '920', first_arcana_number: 9, second_arcana_number: 20, result_arcana_number: 4 },
    { key_number: '922', first_arcana_number: 9, second_arcana_number: 22, result_arcana_number: 20 },
    { key_number: '923', first_arcana_number: 9, second_arcana_number: 23, result_arcana_number: 22 },
    { key_number: '1010', first_arcana_number: 10, second_arcana_number: 10, result_arcana_number: 10 },
    { key_number: '1011', first_arcana_number: 10, second_arcana_number: 11, result_arcana_number: 22 },
    { key_number: '1012', first_arcana_number: 10, second_arcana_number: 12, result_arcana_number: 4 },
    { key_number: '1013', first_arcana_number: 10, second_arcana_number: 13, result_arcana_number: 17 },
    { key_number: '1014', first_arcana_number: 10, second_arcana_number: 14, result_arcana_number: 3 },
    { key_number: '1015', first_arcana_number: 10, second_arcana_number: 15, result_arcana_number: 5 },
    { key_number: '1016', first_arcana_number: 10, second_arcana_number: 16, result_arcana_number: 12 },
    { key_number: '1017', first_arcana_number: 10, second_arcana_number: 17, result_arcana_number: 15 },
    { key_number: '1018', first_arcana_number: 10, second_arcana_number: 18, result_arcana_number: 19 },
    { key_number: '1019', first_arcana_number: 10, second_arcana_number: 19, result_arcana_number: 17 },
    { key_number: '1020', first_arcana_number: 10, second_arcana_number: 20, result_arcana_number: 16 },
    { key_number: '1022', first_arcana_number: 10, second_arcana_number: 22, result_arcana_number: 23 },
    { key_number: '1023', first_arcana_number: 10, second_arcana_number: 23, result_arcana_number: 20 },
    { key_number: '1111', first_arcana_number: 11, second_arcana_number: 11, result_arcana_number: 11 },
    { key_number: '1112', first_arcana_number: 11, second_arcana_number: 12, result_arcana_number: 14 },
    { key_number: '1113', first_arcana_number: 11, second_arcana_number: 13, result_arcana_number: 5 },
    { key_number: '1114', first_arcana_number: 11, second_arcana_number: 14, result_arcana_number: 7 },
    { key_number: '1115', first_arcana_number: 11, second_arcana_number: 15, result_arcana_number: 13 },
    { key_number: '1116', first_arcana_number: 11, second_arcana_number: 16, result_arcana_number: 22 },
    { key_number: '1117', first_arcana_number: 11, second_arcana_number: 17, result_arcana_number: 18 },
    { key_number: '1118', first_arcana_number: 11, second_arcana_number: 18, result_arcana_number: 1 },
    { key_number: '1119', first_arcana_number: 11, second_arcana_number: 19, result_arcana_number: 18 },
    { key_number: '1120', first_arcana_number: 11, second_arcana_number: 20, result_arcana_number: nil },
    { key_number: '1122', first_arcana_number: 11, second_arcana_number: 22, result_arcana_number: 17 },
    { key_number: '1123', first_arcana_number: 11, second_arcana_number: 23, result_arcana_number: 3 },
    { key_number: '1212', first_arcana_number: 12, second_arcana_number: 12, result_arcana_number: 12 },
    { key_number: '1213', first_arcana_number: 12, second_arcana_number: 13, result_arcana_number: 18 },
    { key_number: '1214', first_arcana_number: 12, second_arcana_number: 14, result_arcana_number: 13 },
    { key_number: '1215', first_arcana_number: 12, second_arcana_number: 15, result_arcana_number: 10 },
    { key_number: '1216', first_arcana_number: 12, second_arcana_number: 16, result_arcana_number: 9 },
    { key_number: '1217', first_arcana_number: 12, second_arcana_number: 17, result_arcana_number: 8 },
    { key_number: '1218', first_arcana_number: 12, second_arcana_number: 18, result_arcana_number: 23 },
    { key_number: '1219', first_arcana_number: 12, second_arcana_number: 19, result_arcana_number: 5 },
    { key_number: '1220', first_arcana_number: 12, second_arcana_number: 20, result_arcana_number: 17 },
    { key_number: '1222', first_arcana_number: 12, second_arcana_number: 22, result_arcana_number: 15 },
    { key_number: '1223', first_arcana_number: 12, second_arcana_number: 23, result_arcana_number: 17 },
    { key_number: '1313', first_arcana_number: 13, second_arcana_number: 13, result_arcana_number: 13 },
    { key_number: '1314', first_arcana_number: 13, second_arcana_number: 14, result_arcana_number: 12 },
    { key_number: '1315', first_arcana_number: 13, second_arcana_number: 15, result_arcana_number: 7 },
    { key_number: '1316', first_arcana_number: 13, second_arcana_number: 16, result_arcana_number: 19 },
    { key_number: '1317', first_arcana_number: 13, second_arcana_number: 17, result_arcana_number: 23 },
    { key_number: '1318', first_arcana_number: 13, second_arcana_number: 18, result_arcana_number: 5 },
    { key_number: '1319', first_arcana_number: 13, second_arcana_number: 19, result_arcana_number: 2 },
    { key_number: '1320', first_arcana_number: 13, second_arcana_number: 20, result_arcana_number: nil },
    { key_number: '1322', first_arcana_number: 13, second_arcana_number: 22, result_arcana_number: 0 },
    { key_number: '1323', first_arcana_number: 13, second_arcana_number: 23, result_arcana_number: 1 },
    { key_number: '1414', first_arcana_number: 14, second_arcana_number: 14, result_arcana_number: 14 },
    { key_number: '1415', first_arcana_number: 14, second_arcana_number: 15, result_arcana_number: 0 },
    { key_number: '1416', first_arcana_number: 14, second_arcana_number: 16, result_arcana_number: 10 },
    { key_number: '1417', first_arcana_number: 14, second_arcana_number: 17, result_arcana_number: 19 },
    { key_number: '1418', first_arcana_number: 14, second_arcana_number: 18, result_arcana_number: 23 },
    { key_number: '1419', first_arcana_number: 14, second_arcana_number: 19, result_arcana_number: 1 },
    { key_number: '1420', first_arcana_number: 14, second_arcana_number: 20, result_arcana_number: 9 },
    { key_number: '1422', first_arcana_number: 14, second_arcana_number: 22, result_arcana_number: 9 },
    { key_number: '1423', first_arcana_number: 14, second_arcana_number: 23, result_arcana_number: 0 },
    { key_number: '1515', first_arcana_number: 15, second_arcana_number: 15, result_arcana_number: 15 },
    { key_number: '1516', first_arcana_number: 15, second_arcana_number: 16, result_arcana_number: 1 },
    { key_number: '1517', first_arcana_number: 15, second_arcana_number: 17, result_arcana_number: 11 },
    { key_number: '1518', first_arcana_number: 15, second_arcana_number: 18, result_arcana_number: 7 },
    { key_number: '1519', first_arcana_number: 15, second_arcana_number: 19, result_arcana_number: 9 },
    { key_number: '1520', first_arcana_number: 15, second_arcana_number: 20, result_arcana_number: 6 },
    { key_number: '1522', first_arcana_number: 15, second_arcana_number: 22, result_arcana_number: 7 },
    { key_number: '1523', first_arcana_number: 15, second_arcana_number: 23, result_arcana_number: 7 },
    { key_number: '1616', first_arcana_number: 16, second_arcana_number: 16, result_arcana_number: 16 },
    { key_number: '1617', first_arcana_number: 16, second_arcana_number: 17, result_arcana_number: 23 },
    { key_number: '1618', first_arcana_number: 16, second_arcana_number: 18, result_arcana_number: 9 },
    { key_number: '1619', first_arcana_number: 16, second_arcana_number: 19, result_arcana_number: 4 },
    { key_number: '1620', first_arcana_number: 16, second_arcana_number: 20, result_arcana_number: 18 },
    { key_number: '1622', first_arcana_number: 16, second_arcana_number: 22, result_arcana_number: 13 },
    { key_number: '1623', first_arcana_number: 16, second_arcana_number: 23, result_arcana_number: 13 },
    { key_number: '1717', first_arcana_number: 17, second_arcana_number: 17, result_arcana_number: 17 },
    { key_number: '1718', first_arcana_number: 17, second_arcana_number: 18, result_arcana_number: 14 },
    { key_number: '1719', first_arcana_number: 17, second_arcana_number: 19, result_arcana_number: 20 },
    { key_number: '1720', first_arcana_number: 17, second_arcana_number: 20, result_arcana_number: 10 },
    { key_number: '1722', first_arcana_number: 17, second_arcana_number: 22, result_arcana_number: 14 },
    { key_number: '1723', first_arcana_number: 17, second_arcana_number: 23, result_arcana_number: 19 },
    { key_number: '1818', first_arcana_number: 18, second_arcana_number: 18, result_arcana_number: 18 },
    { key_number: '1819', first_arcana_number: 18, second_arcana_number: 19, result_arcana_number: 3 },
    { key_number: '1820', first_arcana_number: 18, second_arcana_number: 20, result_arcana_number: 0 },
    { key_number: '1822', first_arcana_number: 18, second_arcana_number: 22, result_arcana_number: 19 },
    { key_number: '1823', first_arcana_number: 18, second_arcana_number: 23, result_arcana_number: 14 },
    { key_number: '1919', first_arcana_number: 19, second_arcana_number: 19, result_arcana_number: 19 },
    { key_number: '1920', first_arcana_number: 19, second_arcana_number: 20, result_arcana_number: 13 },
    { key_number: '1922', first_arcana_number: 19, second_arcana_number: 22, result_arcana_number: 4 },
    { key_number: '1923', first_arcana_number: 19, second_arcana_number: 23, result_arcana_number: 10 },
    { key_number: '2020', first_arcana_number: 20, second_arcana_number: 20, result_arcana_number: 20 },
    { key_number: '2022', first_arcana_number: 20, second_arcana_number: 22, result_arcana_number: 10 },
    { key_number: '2023', first_arcana_number: 20, second_arcana_number: 23, result_arcana_number: 15 },
    { key_number: '2222', first_arcana_number: 22, second_arcana_number: 22, result_arcana_number: 22 },
    { key_number: '2223', first_arcana_number: 22, second_arcana_number: 23, result_arcana_number: 2 },
    { key_number: '2323', first_arcana_number: 23, second_arcana_number: 23, result_arcana_number: 23 },
  ]
)
